// Mock data for development
export const mockProjects = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Complete overhaul of company website with new branding and improved user experience",
    progress: 65,
    status: "active",
    dueDate: "2024-01-15",
    priority: "high",
    teamMembers: [
      { name: "Salvi", email: "salvi@company.com", role: "admin" },
      { name: "Archie", email: "archie@company.com", role: "member" },
      { name: "Vinay", email: "vinay@company.com", role: "member" },
      { name: "Arya", email: "arya@company.com", role: "viewer" },
      { name: "Alex Rodriguez", email: "alex@company.com", role: "member" },
    ],
  },
  {
    id: 2,
    name: "Mobile App Development",
    description: "Native iOS and Android app for customer engagement and service delivery",
    progress: 30,
    status: "active",
    dueDate: "2024-02-28",
    priority: "medium",
    teamMembers: [
      { name: "Salvi", email: "salvi@company.com", role: "admin" },
      { name: "Archie", email: "archie@company.com", role: "member" },
      { name: "Vinay", email: "vinay@company.com", role: "member" },
      { name: "Arya", email: "arya@company.com", role: "member" },
      { name: "Chris Lee", email: "chris@company.com", role: "viewer" },
      { name: "Maya Patel", email: "maya@company.com", role: "member" },
      { name: "James Wilson", email: "james@company.com", role: "member" },
      { name: "Sophie Turner", email: "sophie@company.com", role: "member" },
    ],
  },
  {
    id: 3,
    name: "Marketing Campaign Q1",
    description: "Launch comprehensive marketing campaign for Q1 2024 product releases",
    progress: 85,
    status: "active",
    dueDate: "2024-01-10",
    priority: "urgent",
    teamMembers: [
      { name: "Salvi", email: "salvi@company.com", role: "admin" },
      { name: "Archie", email: "archie@company.com", role: "member" },
      { name: "Vinay", email: "vinay@company.com", role: "member" },
      { name: "Arya", email: "arya@company.com", role: "viewer" },
    ],
  },
  {
    id: 4,
    name: "Database Migration",
    description: "Migrate legacy database systems to modern cloud infrastructure",
    progress: 45,
    status: "on-hold",
    dueDate: "2024-03-15",
    priority: "low",
    teamMembers: [
      { name: "Salvi", email: "salvi@company.com", role: "admin" },
      { name: "Archie", email: "archie@company.com", role: "member" },
      { name: "Vinay", email: "vinay@company.com", role: "member" },
    ],
  },
  {
    id: 5,
    name: "Customer Portal",
    description: "Self-service customer portal with account management and support features",
    progress: 100,
    status: "completed",
    dueDate: "2023-12-20",
    priority: "medium",
    teamMembers: [
      { name: "Salvi", email: "salvi@company.com", role: "admin" },
      { name: "Archie", email: "archie@company.com", role: "member" },
      { name: "Vinay", email: "vinay@company.com", role: "member" },
      { name: "Arya", email: "arya@company.com", role: "viewer" },
    ],
  },
]

export const mockTasks = [
  {
    id: 1,
    projectId: 1,
    title: "Design Homepage Layout",
    description: "Create wireframes and mockups for the new homepage design",
    status: "completed",
    priority: "high",
    assignee: "Archie",
    dueDate: "2024-01-05",
    createdAt: "2023-12-15",
  },
  {
    id: 2,
    projectId: 1,
    title: "Implement Navigation Menu",
    description: "Build responsive navigation with dropdown menus",
    status: "in-progress",
    priority: "medium",
    assignee: "Salvi",
    dueDate: "2024-01-08",
    createdAt: "2023-12-16",
  },
  {
    id: 3,
    projectId: 1,
    title: "Content Migration",
    description: "Migrate existing content to new CMS structure",
    status: "todo",
    priority: "low",
    assignee: "Vinay",
    dueDate: "2024-01-12",
    createdAt: "2023-12-18",
  },
  {
    id: 4,
    projectId: 2,
    title: "User Authentication Flow",
    description: "Implement secure login and registration system",
    status: "in-progress",
    priority: "high",
    assignee: "Salvi",
    dueDate: "2024-01-20",
    createdAt: "2023-12-20",
  },
  {
    id: 5,
    projectId: 2,
    title: "Push Notifications Setup",
    description: "Configure push notification service for both platforms",
    status: "todo",
    priority: "medium",
    assignee: "Archie",
    dueDate: "2024-02-01",
    createdAt: "2023-12-22",
  },
]
